### ISSUE TITLE
Refresh/ Zoom-out map - Clicking on the Australian semi... [LACE]

### ISSUE THREAD

**Issue by nfreear** [mhawksey/wp-evidence-hub#40]
> "Clicking on the Australian semi circle makes Australia very big – with no indication of how to return to the world map."

**Comment by mhawksey** [comment]
ah hadn't spotted that - looks good

**Comment by nfreear** [comment]
Hi Martin,

It took a few iterations, but we now have a solution which works for both the ` d3.js ` map (country-map) and the ` Leaflet.js ` ones (evidence, project maps) ...

[@github.com/IET-OU/wp-evidence-hub `../shortcodes/class-shortcode.php` ~ line 309..](https://github.com/IET-OU/wp-evidence-hub/blob/5180467ebe93e64240cddecbd061474a5f7a29f4/shortcodes/class-shortcode.php#L309-324) :

```html
<script>
var OERRH = OERRH || {};

OERRH.resetMap = function () {
	// D3.js map.
	if (window.displaySankey) {
		displaySankey();  //'World'
	}
	// Leaflet.JS map.
	else if (OERRH.geomap && OERRH.geomap.map.setView) {
		OERRH.geomap.map.setView(OERRH.geomap.center || [25, 0], 2);
	}
	return false;
};
</script>
<a href="#!zoom-out" id="map-reset-button" onclick="return OERRH.resetMap()"> ... </a>
```

Deployed to live:

* http://evidence.laceproject.eu/projects/projects-map/
* http://evidence.laceproject.eu/evidence/country-map/

Nick
