### ISSUE TITLE
Add a 'composer.json' - switch from Git submodules to composer ...

### ISSUE THREAD

**Issue by nfreear** [mhawksey/wp-evidence-hub#41]
I'll work on this! See,

* https://roots.io/using-composer-with-wordpress/
* http://wpackagist.org/
* http://composer.json.jolicode.com/
* https://gist.github.com/nfreear/8cbebb09cfb235140494

..

**Comment by nfreear** [comment]
Deployed live this morning:

* http://evidence.laceproject.eu/

You can see the wrapper/ parent project here:

* https://github.com/IET-OU/oer-evidence-hub-org/tree/CR40-composer

Closing.


Nick

**Comment by mhawksey** [comment]
nice work :+1:
