### ISSUE TITLE
Fixing Strict Standard notice in dev mode

### ISSUE THREAD

**Issue by nfreear** [mhawksey/wp-evidence-hub#44]
* Commit: https://github.com/cftp/facetious/commit/a184ac0c133a55ed9974a838df339d3addac1e8b -- @philipjohn on Feb 6, 2014.

**Comment by nfreear** [comment]
Hi Martin, thanks for this fix - v. fast! (Also, thanks for the #42 adjustment..)

Yours,

Nick

**Comment by mhawksey** [comment]
not a prob - was doing some other repo work
