### ISSUE TITLE
Option to add a key below the [geomap]

### ISSUE THREAD

**Issue by nfreear** [mhawksey/wp-evidence-hub#48]
Relates to: #47.

**Comment by mhawksey** [comment]
Rob was also asking for this ...

**Comment by nfreear** [comment]
Hi Martin,

Actually, for the moment I've ended up doing it as part of the normal WordPress page-content ...

* http://iet-lace-approval.open.ac.uk/evidence/evidence-map/#key

...With some CSS:

* [IET-OU/wp-evidence-hub .../css/style.css ~ line 1742](https://github.com/IET-OU/wp-evidence-hub/blob/master/css/style.css#L1742) (a big file!)
* https://github.com/IET-OU/wp-evidence-hub/commit/274b215585c9e82974f40a97dd824755c3e586a5

**Comment by nfreear** [comment]
Hi Martin,

This is implemented - see our test server:

* http://iet-lace-approval.open.ac.uk/evidence/evidence-map/#key

Note the key is displayed by default:

```
    [geomap display_key="true"]
```

And, it should display the correct markers depending on `type`:

```
    [geomap type="policy" display_key="true"]
```

Yours,


Nick

**Comment by nfreear** [comment]
Deployed. In use:

* http://evidence.laceproject.eu/projects/projects-map/#key

Closing

Nick
