### ISSUE TITLE
Option to do something better with evidence that has no location - evidence map [LACE]+

### ISSUE THREAD

**Issue by nfreear** [mhawksey/wp-evidence-hub#50]
Hi,

This issue, like #47 is a use-case for #49.

If you look at the live site, you'll see a cluster of evidence in the sea just west of Africa - below Ghana:

* http://evidence.laceproject.eu/evidence/evidence-map/

This is evidence that has no location, either because it is global in nature, the location is unknown, or it is simply missing. So it ends up at ` [ 0, 0 ] `. This doesn't look great - it's in the centre of the map, noticeable, and confusing.

I'm proposing an option (and it would be an option) to re-position the evidence off to one side - where it is less noticeable. See the LACE test server for an example:

* http://iet-lace-approval.open.ac.uk/evidence/evidence-map/

Most of the work happens in ` leaflet-map.js `, with Javascript configuration added in the PHP.

Thoughts?

Nick

**Comment by nfreear** [comment]
Hi,

I've put the work for this on a branch,

* [IET-OU/wp-evidence-hub `@CR50-geomap ` .../js/leaflet-map.js](https://github.com/IET-OU/wp-evidence-hub/blob/CR50-geomap/js/leaflet-map.js#L128)

The test ...

```js
var near_zero = function (degrees) {
    return Math.abs(degrees) < 2;
}

//...

if (OERRH.geomap.no_location_latlng && near_zero(coord[0]) && near_zero(coord[1])) {

    // Re-locate ...

```

**Comment by mhawksey** [comment]
We should legend the area Limbo ;)

**Comment by nfreear** [comment]
We did (almost) seriously talk about creating a new location &mdash; a new country &mdash; an island called ` Evidência `....?!

**Comment by nfreear** [comment]
Deployed to live, 21 May:

* http://evidence.laceproject.eu/evidence/evidence-map/#evidence-map
* [IET task: #3513611](https://iet.teamworkpm.net/tasks/3513611)
