### ISSUE TITLE
Add a minimum zoom to evidence-map [LACE]

### ISSUE THREAD

**Issue by nfreear** [mhawksey/wp-evidence-hub#51]
Hi,

I get frustrated when trying to scroll down the page (on my Macbook) - instead I sometimes zoom out on the evidence-map, so that everything is tiny!

I'd like to put a minimum zoom on the map - if initial zoom is set to ` 2 `, perhaps ` { minZoom: 1 } `? This  should improve usability:

* http://leafletjs.com/reference.html#map-minzoom

I can't think when we'd want to zoom-out?!

N.

**Comment by mhawksey** [comment]
Agree - can't think of a reason why <1 would be required

**Comment by nfreear** [comment]
Deployed to LACE ~ 21 May. Closing.

* http://evidence.laceproject.eu/evidence/evidence-map/
